### ISSUE TITLE
the cargo.lock refers to local paths

### ISSUE THREAD

**Issue by happysalada** [fdncred/nu_plugin_regex#3]
so that means we can't build this crate just by downloading the source code.
Would you mind making a release with just versions for the dependencies and no local paths ?

Thanks a lot for making this!

**Comment by fdncred** [comment]
I haven't made any releases. Feel free to clone and change the Cargo.toml. I try to keep all my plugins in sync with the nushell main branch.

**Comment by happysalada** [comment]
Ah, i understand.
Nixos wants to build the plugin from source and if i forked it it would seem really weird to an outside user.
Lets wait until the api stabilizes a bit then and your comfortable using just a version number.
Thank you for your response !
