### ISSUE TITLE
Unable to install plugin

### ISSUE THREAD

**Issue by cronhan** [fdncred/nu_plugin_regex#6]
Hi, 

when trying to install the plugin I am getting an error:

```
cargo install nu_plugin_regex
    Updating crates.io index
error: could not find `nu_plugin_regex` in registry `crates-io` with version `*`
```

What am I doing wrong? Thanks!

**Comment by fdncred** [comment]
> What am I doing wrong? Thanks!

You're assuming nu_plugin_regex is published on crates.io, which it isn't. In order to install this plugin, you'll probably have to build it the way I do which is clone this repo, clone the nushell repo in a sibling folder, and run `cargo install --path .` from within the nu_plugin_regex folder.

**Comment by cronhan** [comment]
Okay, thanks for the feedback. I assumed to use the command I used because there is no "how to install" on the readme.

**Comment by fdncred** [comment]
Agreed. There should be a how to install. I'd accept a PR for that.
