### ISSUE TITLE
Tags on Release Commits

### ISSUE THREAD

**Issue by Talia-12** [fdncred/nu_plugin_regex#9]
Would it be doable for you to add a tag to commits that you're publishing/have published to crates.io? It would make packaging for nixpkgs a bit cleaner.

**Comment by fdncred** [comment]
maybe, if i can remember? how does it make it cleaner?

**Comment by Talia-12** [comment]
here's an example of the kind of code that you see in a nix package, fetching the source code of the thing being packaged:
```
src = fetchFromGitHub {
  owner = "fennewald";
  repo = "nu_plugin_net";
  rev = "refs/tags/${version}";
  hash = "sha256-GOF2CSlsjI8PAmIxj/+mR01X5XMviEM8gj7ZYTbeX7I=";
};
```
if there's no tag to target the fetch of of you instead would have, e.g.,
```
rev = "c41f98632a538cad38ed0dd518340fb8eb28274e";
```
which works, but is significantly uglier and also significantly less readable as to why that git commit in particular was picked.

**Comment by fdncred** [comment]
make sense. let's see if i remember next time. maybe i should just leave this open until then as a reminder?

**Comment by Talia-12** [comment]
It should be pretty easy to go back and tag the commits that you made releases? I don't know if github has something inbuilt to do it, but if you grab the commit id you can tag that commit from the command line with e.g.
```
git tag 0.6 c41f98632a538cad38ed0dd518340fb8eb28274e
```
and then push that tag to github with `git push origin --tags`.

**Comment by aidalgol** [comment]
It would also be beneficial to users getting the package from crates.io, because it lets them see which commit a given version was built from.

**Comment by fdncred** [comment]
i remembered, yay me!
